sonar.projectKey=cinesfera-IS2_cinesfera
sonar.organization=cinesfera-is2

sonar.sources=backend/app,frontend/app,frontend/features,frontend/lib
sonar.exclusions=frontend/**/*.test.ts,frontend/**/*.test.tsx
sonar.tests=backend/tests,frontend/app,frontend/features,frontend/lib
sonar.test.inclusions=backend/tests/**/*.py,frontend/**/*.test.ts,frontend/**/*.test.tsx

sonar.python.version=3.14
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

# Hace fallar el job de CI si el análisis no pasa el Quality Gate.
sonar.qualitygate.wait=true
